---
version: '3'

services:
  app:
    build: .
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongo/cha-notifier
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: npm run dev:docker
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.7@sha256:50674e3e315d680beaeab904f7a24c87d2ba6ffe5132897cef664baf0d56cc26
    volumes:
      - mongo:/data/db

volumes:
  mongo:
