---
version: '3'

services:
  app:
    build: .
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongo/cha-notifier
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: npm run dev:docker
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.9@sha256:736eec20a17eafaa988d299902fcaab521cb0ca56af4400f782576afc878d6bc
    volumes:
      - mongo:/data/db

volumes:
  mongo:
