---
version: '3'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file: .env
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo/cha-notifier
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.3@sha256:d969194a7c4dcd817cae5dc726b1493547a3ad3f1b30f7f58857adc9ae6a4483
    volumes:
      - mongo:/data/db

volumes:
  mongo:
