---
version: '3'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file: .env
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo/cha-notifier
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.9@sha256:a4fe8722970f7a10ec73820f1f43ae930724267c249a9ac12d42d3fdc2a17167
    volumes:
      - mongo:/data/db

volumes:
  mongo:
